// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuB1SKyOUwmyFkTXLQRTCg826XH1iWjU8',
    appId: '1:492691104119:web:0b4190f169b09e688c0172',
    messagingSenderId: '492691104119',
    projectId: 'tejara-store',
    authDomain: 'tejara-store.firebaseapp.com',
    storageBucket: 'tejara-store.firebasestorage.app',
    measurementId: 'G-1TH195WGX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhxvmVYZT-k5cTsoez1aQN2dtcdwmEZu4',
    appId: '1:492691104119:android:4a0236a65557c2658c0172',
    messagingSenderId: '492691104119',
    projectId: 'tejara-store',
    storageBucket: 'tejara-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_XByfacdmwyihivXTQQVxIexHi_bIMlU',
    appId: '1:492691104119:ios:6dedf9e535c37ca08c0172',
    messagingSenderId: '492691104119',
    projectId: 'tejara-store',
    storageBucket: 'tejara-store.firebasestorage.app',
    iosBundleId: 'com.example.tejaraStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_XByfacdmwyihivXTQQVxIexHi_bIMlU',
    appId: '1:492691104119:ios:6dedf9e535c37ca08c0172',
    messagingSenderId: '492691104119',
    projectId: 'tejara-store',
    storageBucket: 'tejara-store.firebasestorage.app',
    iosBundleId: 'com.example.tejaraStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuB1SKyOUwmyFkTXLQRTCg826XH1iWjU8',
    appId: '1:492691104119:web:60a40bb75f6fedcf8c0172',
    messagingSenderId: '492691104119',
    projectId: 'tejara-store',
    authDomain: 'tejara-store.firebaseapp.com',
    storageBucket: 'tejara-store.firebasestorage.app',
    measurementId: 'G-GBVPW8SSH1',
  );
}
